---
title: "Make dummy data"
output: html_notebook
---

We need a dummy data set to figure out what is going on here with cleaning the data.  I'm going to reduce the big data set to 50 observations and then fake them to have some repeats of various types.

```{r}
rm(list = ls())
library(dplyr)
library(magrittr)
library(stringr)
library(tidyr)
library(ggplot2)

library(readr)
DF<- read_csv("/Users/ebar/Dropbox/R/JSON/no-co-wild-phase-1-_1Apr_classifications.csv-flattened.csv")
```


Let's reduce the dataset
```{r}
DF<-sample_n(DF, 20)

```
And see what you got:
```{r}
DF %>% summarise(
     num_subjects = n_distinct(subject_ids),
     num_class = n_distinct(classification_id)
)
```


Now mess with the data
```{r}
DF$subject_ids<-c(1,2, 3, 4, 4, 5, 6, 7,7,7, 8, 9,9,9,9,9, 10, 10, 11, 12)
DF$choice<-c("NOTHINGHERE", "WHITETAILEDDEER", "COYOTE", "REDSQUIRREL", "GRAYSQUIRREL", "PORCUPINE", "SOMETHINGHERE", "BOBCAT", "DOMESTICCAT", "DOMESTICCAT","PORCUPINE", "PORCUPINE", "COTTONTAIL", "RACCOON", "DOMESTICCAT", "BOBCAT", "GRAYSQUIRREL", "GRAYSQUIRREL", "PORCUPINE", "PORCUPINE")
DF$classification_id<-c(1:20)

```

Now save for cleaning

```{r}
write.csv(DF, "dummy_flattened_to_clean.csv")
```

