---
title: "Extracting subject data"
author: "Erika"
date: "12/03/2018"
output: html_document
---
###Introduction
We are using the [Zooniverse](https://zooniverse.org) platform to score pictures
from game cameras.  The process for getting the pictures into the platform is pretty straightforward though somewhat time consuming.  However, once you download the classification, the difficulty goes way up.

Data arrive as a csv file in JSON format.  Some columns in the data are very straighforward
and act just like "normal" columns in e.g. an excel spreadsheet or an R data frame.
However, other columns, especially the "annotation" column (which contains all of the interesting classification info such as species ID) comes in as a JSON "array".  Each row in the column contains an array with mutiple pieces of information.  Sort of like a new csv in a single column.

This R project is set up so that I can work through data preparation for some example zooniverse projects to start
understanding how to deal with the files.  Much of the information I'm using and working with comes from the Zooniverse [Data-Digging-Code-Repository](https://github.com/zooniverse/Data-digging) on GitHub.  In particular, the links there to Ali Burchard's R code in her [Data Processing git repository](https://github.com/aliburchard/DataProcessing) is being used or modified here. I've downloaded the files from this git repository and dropped them in the folder for this project.

In the "ProjectIntroduction.Rmd" file associated with this project, I used the above stuff to run a test with some data from a Michigan project.  Here I'm going to play with modifying that code to try to flatten my own data.

### Trying it out
First I'm going to copy the code I used for the practice data and paste it below.
Second, I'm going to use some code from Ivan Ramler (saved in Accessing_habitat.R) to pull just the habitat data.

#####Step 1
Set up the workspace and load functions
```{R}
rm(list = ls())
#devtools::install_github("sailthru/tidyjson") #install tidyjson if needed
library(tidyjson)
library(magrittr)
#library(rjson)
library(jsonlite)
library(dplyr)
library(stringr)
library(tidyr)
library(lubridate)

source(file = "DataProcessing-master/projects/survey-tasks/generalized/flattening_script.R")
```
Nothing in the above needed changing.
#####Step 2 Clean classification data and specify fields

First specify the project
```{R}
project_name <- "mammalogy"  ## change project name
classifications_file <- "test-workflow-classifications.csv" ##Change input file
```

Next load and take a quick look at the data
```{R}
jdata <- read_csv(classifications_file)
head(jdata)
```
You can see that there is a column containing an array of key: value pairs called subject_data.  I'd like to be able to extract the habitat information from subject data.

Here's what Ivan provided
```{r}
library(purrr) #also requires jsonlite but it was loaded above

subjects<-purrr::map(jdata$subject_data, jsonlite::fromJSON, flatten = T)
#this brought in the subject_data as a list of 75 items
habitat<-sapply(subjects, function(x)x[[1]]$Habitat, simplify = T)
```
Created a new variable called habitat with the information I need!




